spring:
  application:
    name: study

  config:
    import: aws-parameterstore:/camp-health-app/prod/

  cloud:
    aws:
      region:
        static: ap-northeast-2
      credentials:
        instance-profile: true
      s3:
        bucket: "test-profile-images-banhklo2"

  datasource:
    url: jdbc:mysql://my-database.cba2immmcc2m.ap-northeast-2.rds.amazonaws.com:3306/test
    username: admin
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: info,health
  info:
    env:
      enabled: true
