spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: admin
    password: 12345678

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  cloud:
    aws:
      parameterstore:
        enabled: false
      secretsmanager:
        enabled: false

      region:
        auto: false
        static: ap-northeast-2

      s3:
        enabled: true
        bucket: "test-profile-images-banhklo2"
